name: test project 
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'    
      - name: install reiquirments
        run: pip install -r requirements.txt
      - name: Install dbt
        run: pip install dbt-core dbt-sqlserver
      - name: run test data quality 
        run: pytest tests/test_data_quality.py 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'    
      - name: install reiquirments
        run: pip install -r requirements.txt
      - name: generate artifact
        run: python build_output.py
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: transformed_data
          path: |
            data/clean_sales.csv
            data/sales_by_category.csv
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: transformed_data
      # - name: get Code
      #   uses: actions/checkout@v7
      # - name: install Python 
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: '3.11'    
      # - name: install reiquirments
      #   run: pip install -r requirements.txt
      # - name: Install dbt
      #   run: pip install dbt-core dbt-sqlserver
      # - name: deploy 
      #   run: echo "deploy is done"